version: "3"
services:
  php:
    container_name: php_${PROJECT_NAME}
    build:
      context: ./
      dockerfile: docker/configs/php/Dockerfile
      args:
        WORKDIR: ${WORKDIR}
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    environment:
      WORKDIR: ${WORKDIR}
      XDEBUG_CONFIG: remote_host={{YOUR_IP_ADDRESS}}
      PHP_IDE_CONFIG: serverName=docker
    volumes:
      - ./:${WORKDIR}
      - ./mails:/var/www/mail
    links:
      - db_mysql

  db_mysql:
    image: mysql:latest
    container_name: mysql_${PROJECT_NAME}
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      WORKDIR: ${WORKDIR}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123}
      MYSQL_DATABASE:  ${MYSQL_DATABASE:-db}
      MYSQL_USER:  ${MYSQL_USER:-root}
      MYSQL_PASSWORD:  ${MYSQL_PASSWORD:-pass}
    volumes:
      - ./docker/databases/mysql_dump:/docker-entrypoint-initdb.d
